version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  runtime:
    'win81-x64'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: >-
    dotnet restore .\Src\HoneyBear.Alexa.Calculator

    dotnet build .\Src\HoneyBear.Alexa.Calculator -c $env:CONFIGURATION -r $env:RUNTIME

    dotnet publish .\Src\HoneyBear.Alexa.Calculator -c $env:CONFIGURATION -r $env:RUNTIME

    Copy-Item .\Src\HoneyBear.Alexa.Calculator\bin\$env:CONFIGURATION\netcoreapp1.0\$env:RUNTIME\HoneyBear.Alexa.Calculator.deps.json .\Src\HoneyBear.Alexa.Calculator\bin\$env:CONFIGURATION\netcoreapp1.0\$env:RUNTIME\publish\

    Compress-Archive .\Src\HoneyBear.Alexa.Calculator\bin\$env:CONFIGURATION\netcoreapp1.0\$env:RUNTIME\publish\* .\HoneyBear.Alexa.Calculator.zip
test: off
artifacts:
- path: HoneyBear.Alexa.Calculator.zip
  name: HoneyBear.Alexa.Calculator
deploy: off
