version: 1.0.{build}
skip_tags: true
configuration: Release
environment:
  project:
    'HoneyBear.Alexa.Calculator'
  runtime:
    'win81-x64'
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    appveyor-retry dotnet restore -v Minimal

    $json = Get-Content .\Src\$env:PROJECT\project.json -raw | ConvertFrom-Json

    $json.version = $env:APPVEYOR_BUILD_VERSION

    $json | ConvertTo-Json | Set-Content .\Src\$env:PROJECT\project.json
build_script:
- ps: >-
    dotnet build .\Src\$env:PROJECT -c $env:CONFIGURATION -r $env:RUNTIME
after_build:
- ps: >-
    dotnet publish .\Src\$env:PROJECT -c $env:CONFIGURATION -r $env:RUNTIME

    Copy-Item .\Src\$env:PROJECT\bin\$env:CONFIGURATION\netcoreapp1.0\$env:PROJECT.deps.json .\Src\$env:PROJECT\bin\$env:CONFIGURATION\netcoreapp1.0\$env:RUNTIME\publish\

    Compress-Archive .\Src\$env:PROJECT\bin\$env:CONFIGURATION\netcoreapp1.0\$env:RUNTIME\publish\* .\artifacts\$env:PROJECT.zip
test: off
deploy: off
artifacts:
- path: artifacts\**\*.*
